// IR → Verilog string. Deterministic pretty printer.
//
// Determinism contract:
//   - Ports emitted in IRModule.ports order (declaration order).
//   - Nets emitted in IRModule.nets order (fromCircuit sorts deterministically).
//   - Instances emitted in IRModule.instances order.
//   - No Date.now(), Math.random(), or Map iteration without sorting.
//   - Header is optional (opts.header); when present, its date is the caller's
//     responsibility — do not include Date.now() by default so round-trip
//     diffs ignore headers naturally.

import { IR_KIND, PORT_DIR } from './types.js';

function widthSpec(w) {
  return w > 1 ? `[${w - 1}:0] ` : '';
}

function emitExpr(expr) {
  if (!expr) return '/*<null>*/';
  switch (expr.kind) {
    case IR_KIND.Ref:
      return expr.netName;
    case IR_KIND.Slice:
      if (expr.hi === expr.lo) return `${expr.netName}[${expr.lo}]`;
      return `${expr.netName}[${expr.hi}:${expr.lo}]`;
    case IR_KIND.Literal:
      return `${expr.width}'h${(BigInt(expr.value) & ((1n << BigInt(expr.width)) - 1n)).toString(16)}`;
    case IR_KIND.BinaryOp:
      return `(${emitExpr(expr.left)} ${expr.op} ${emitExpr(expr.right)})`;
    case IR_KIND.UnaryOp:
      return `(${expr.op}${emitExpr(expr.operand)})`;
    case IR_KIND.Concat:
      return `{${expr.parts.map(emitExpr).join(', ')}}`;
    case IR_KIND.Replicate:
      return `{${expr.count}{${emitExpr(expr.inner)}}}`;
    case IR_KIND.ZeroExtend: {
      const pad = expr.width - expr.inner.width;
      if (pad <= 0) return emitExpr(expr.inner);
      return `{${pad}'b0, ${emitExpr(expr.inner)}}`;
    }
    case IR_KIND.SignExtend: {
      const pad = expr.width - expr.inner.width;
      if (pad <= 0) return emitExpr(expr.inner);
      const inner = emitExpr(expr.inner);
      return `{{${pad}{${inner}[${expr.inner.width - 1}]}}, ${inner}}`;
    }
    default:
      return `/*<${expr.kind}>*/`;
  }
}

function emitPortConnection([portName, expr]) {
  return `.${portName}(${emitExpr(expr)})`;
}

function emitInstance(inst) {
  const entries = Object.entries(inst.portMap).sort(
    (a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0,
  );
  const conns = entries.map(emitPortConnection).join(', ');
  const params = Object.entries(inst.params).sort(
    (a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0,
  );
  const paramStr = params.length
    ? ` #(${params.map(([k, v]) => `.${k}(${v})`).join(', ')})`
    : '';
  return `  ${inst.type}${paramStr} ${inst.instanceName} (${conns});`;
}

function emitAssign(a) {
  return `  assign ${emitExpr(a.lhs)} = ${emitExpr(a.rhs)};`;
}

export function toVerilog(ir, opts = {}) {
  const { header = false, headerText = null } = opts;
  const lines = [];
  if (header) {
    if (headerText) {
      for (const ln of String(headerText).split('\n')) lines.push(`// ${ln}`);
    } else {
      lines.push('// Generated by Circuit Designer — HDL Toolchain');
    }
    lines.push('');
  }

  const portDecls = ir.ports.map(p => {
    const dir = p.dir === PORT_DIR.INPUT ? 'input '
              : p.dir === PORT_DIR.OUTPUT ? 'output'
              : 'inout ';
    return `${dir} ${widthSpec(p.width)}${p.name}`;
  });

  if (portDecls.length === 0) {
    lines.push(`module ${ir.name};`);
  } else {
    lines.push(`module ${ir.name}(`);
    lines.push(portDecls.map(d => '  ' + d).join(',\n'));
    lines.push(');');
  }

  if (ir.nets.length > 0) {
    lines.push('');
    for (const net of ir.nets) {
      lines.push(`  ${net.netKind} ${widthSpec(net.width)}${net.name};`);
    }
  }

  const bodyLines = [];
  for (const a of ir.assigns) bodyLines.push(emitAssign(a));
  for (const inst of ir.instances) bodyLines.push(emitInstance(inst));
  if (Array.isArray(ir._unmapped)) {
    for (const u of ir._unmapped) {
      bodyLines.push(`  // TODO: translator for ${u.type} (${u.nodeId}) not yet implemented`);
    }
  }
  if (bodyLines.length > 0) {
    lines.push('');
    lines.push(...bodyLines);
  }

  lines.push('');
  lines.push('endmodule');
  lines.push('');
  return lines.join('\n');
}
