// VerilogExporter — public entry for circuitJSON → Verilog.
//
// Three-stage pipeline:
//   1. validateCircuit → HDLError[]  (warnings surfaced, errors halt export)
//   2. fromCircuit     → IRModule    (structural, width-explicit IR)
//   3. toVerilog       → string      (deterministic pretty print)
//
// Identifier sanitization is re-exported from core/identifiers.js so that
// existing callers (Phase 1 tests) continue to import it from this module.

import { validateCircuit, hasBlockingErrors } from './core/CircuitValidator.js';
import { fromCircuit } from './ir/fromCircuit.js';
import { toVerilog } from './ir/toVerilog.js';
import { hasTranslator } from './translators/index.js';

export { sanitizeIdentifier } from './core/identifiers.js';
export { HDLError, SEVERITY } from './core/HDLError.js';

// Determinism contract: exportCircuit output is byte-identical across runs
// for a given circuitJSON. A timestamp is emitted ONLY when the caller opts
// in with `timestamp: true`; without it, round-trip (export → copy → import
// → re-export) produces identical bytes.
function buildHeaderText({ header, timestamp }) {
  if (!header) return null;
  const line1 = 'Generated by Circuit Designer — HDL Toolchain';
  if (!timestamp) return line1;
  return `${line1}\nExported: ${new Date().toISOString()}`;
}

export function exportCircuit(circuitJSON, options = {}) {
  const opts = {
    topName: 'top',
    header: true,
    timestamp: false,
    ...options,
  };

  const errors = validateCircuit(circuitJSON, { hasTranslator });
  if (hasBlockingErrors(errors) && !opts.force) {
    // Blocking errors → throw the first. Callers that want the full list
    // should call validateCircuit directly or use exportCircuitWithDiagnostics.
    const first = errors.find(e => e.severity === 'error');
    throw first;
  }

  const ir = fromCircuit(circuitJSON);
  ir.name = opts.topName;

  return toVerilog(ir, {
    header: !!opts.header,
    headerText: buildHeaderText(opts),
  });
}

// Power-user entry: returns Verilog + diagnostic list + IR, never throws.
export function exportCircuitWithDiagnostics(circuitJSON, options = {}) {
  const opts = { header: true, timestamp: false, ...options };
  const errors = validateCircuit(circuitJSON, { hasTranslator });
  const ir = fromCircuit(circuitJSON);
  ir.name = opts.topName || 'top';
  const verilog = toVerilog(ir, {
    header: !!opts.header,
    headerText: buildHeaderText(opts),
  });
  return { verilog, errors, ir };
}
